version: "3.7"
services:

  # Snapshot hub
  snapshot-hub:
    build: .
    container_name: snapshot-hub
    env_file:
      - .env.local
    depends_on:
      - snapshot-mysql
    ports:
      - "8080:8080"

  # Snapshot MySQL instance
  snapshot-mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    container_name: snapshot-mysql
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "snapshot"
    volumes:
        - ./server/helpers/database/:/docker-entrypoint-initdb.d
        - ./server/helpers/datadir/:/var/lib/mysql
    ports:
        - "3306:3306"

networks:
  default:
    name: snapshot-network
